// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiKitWeb.Context;

namespace apiKitWeb.Migrations
{
    [DbContext(typeof(KitWebsDbContext))]
    [Migration("20190612045727_Jeffer")]
    partial class Jeffer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apiKitWeb.Entity.KitNet", b =>
                {
                    b.Property<int>("KitNetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CEP");

                    b.Property<string>("Descricao");

                    b.Property<string>("Endereco");

                    b.Property<string>("Localizacao");

                    b.Property<string>("Numero");

                    b.Property<string>("Preco");

                    b.Property<string>("Referencia");

                    b.Property<int>("UsuarioId");

                    b.HasKey("KitNetId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("KitNets");
                });

            modelBuilder.Entity("apiKitWeb.Entity.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMail");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("apiKitWeb.Entity.KitNet", b =>
                {
                    b.HasOne("apiKitWeb.Entity.Usuario", "Usuario")
                        .WithMany("KitNets")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
